# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# and this guide: https://towardsdatascience.com/travis-ci-for-r-advanced-guide-719cb2d9e0e5

language: R
sudo: false
cache: packages
latex: false
fortran: false

matrix:
  include:
    - r: release
      os: linux
      r_packages:
      - covr
      - rgdal
      after_success:
      - tar -C .. -xf $PKG_TARBALL
      - Rscript -e 'covr::codecov()'

r_github_packages:
      - rstudio/reticulate

before_script:
  - sudo apt-get update
  - sudo apt-get install libgdal1i
  - sudo apt install libgdal-dev
  - sudo apt install libproj-dev
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .

env:
  - _R_CHECK_FORCE_SUGGESTS_=false
