# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# and this guide: https://towardsdatascience.com/travis-ci-for-r-advanced-guide-719cb2d9e0e5

language: r

r: release

r_packages:
  - covr
  - rgdal

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'

r_github_packages:
  - rstudio/reticulate

before_install:
  - sudo apt-get update
  - sudo apt-get install libgdal-dev
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  
before_script:
  - R CMD INSTALL .

env:
  - _R_CHECK_FORCE_SUGGESTS_=false
